name: Metrics
on:
  # Roda automaticamente a cada 12 horas
  schedule: [{cron: "0 */12 * * *"}]
  # Permite que você execute manualmente pela aba Actions do GitHub
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Real-time metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Mostra apenas o cabeçalho curto e os repositórios, tirando a poluição de texto
          base: header, repositories
          # Tema moderno com fundo escuro elegante
          config_theme: tokyonight
          # Linguagens mais usadas
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 5
